import { ACCEPTED_WORD_SET } from "./accepted-words.js";

const ALBANIAN_DIGRAPHS = new Set([
  "dh",
  "gj",
  "ll",
  "nj",
  "rr",
  "sh",
  "th",
  "xh",
  "zh",
]);

const ALBANIAN_SINGLE_LETTERS = new Set([
  "a",
  "b",
  "c",
  "ç",
  "d",
  "e",
  "ë",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "x",
  "y",
  "z",
]);

function tokenizeAlbanian(word) {
  const normalizedWord = word.normalize("NFC").toLocaleLowerCase("sq-AL");
  const tokens = [];

  for (let index = 0; index < normalizedWord.length; ) {
    const pair = normalizedWord.slice(index, index + 2);

    if (ALBANIAN_DIGRAPHS.has(pair)) {
      tokens.push(pair);
      index += 2;
      continue;
    }

    const letter = normalizedWord[index];
    if (!ALBANIAN_SINGLE_LETTERS.has(letter)) {
      return null;
    }

    tokens.push(letter);
    index += 1;
  }

  return tokens;
}

const ANSWER_ENTRIES = [
  {
    word: "anije",
    partOfSpeech: "emër",
    syllables: "a-ni-je",
    clue: "Lundron nga porti në port.",
    definition: "Mjet i madh lundrues për transportin e njerëzve ose të mallrave.",
    example: "Anija u nis herët nga porti.",
    region: "standard",
  },
  {
    word: "ardhje",
    partOfSpeech: "emër",
    syllables: "ardh-je",
    clue: "E kundërta e një nisjeje.",
    definition: "Veprimi i mbërritjes së dikujt ose të diçkaje në një vend.",
    example: "Ardhja e trenit u njoftua në stacion.",
    region: "standard",
  },
  {
    word: "arushë",
    partOfSpeech: "emër",
    syllables: "a-ru-shë",
    clue: "Banore e pyllit me putra të fuqishme.",
    definition: "Ari i gjinisë femërore.",
    example: "Arusha i mbrojti të vegjlit e saj.",
    region: "standard",
  },
  {
    word: "babai",
    partOfSpeech: "emër",
    syllables: "ba-ba-i",
    clue: "Një nga dy prindërit.",
    definition: "Prindi mashkull i një fëmije.",
    example: "Babai po lexon një libër.",
    region: "standard",
  },
  {
    word: "bagazh",
    partOfSpeech: "emër",
    syllables: "ba-gazh",
    clue: "E merr me vete në udhëtim.",
    definition: "Tërësia e valixheve dhe sendeve që merr një udhëtar.",
    example: "Bagazhi ynë ishte gati për nisje.",
    region: "standard",
  },
  {
    word: "bardhë",
    partOfSpeech: "mbiemër",
    syllables: "bar-dhë",
    clue: "Ngjyra e borës së freskët.",
    definition: "Që ka ngjyrën më të çelët, si bora ose qumështi.",
    example: "Ajo veshi një këmishë të bardhë.",
    region: "standard",
  },
  {
    word: "besim",
    partOfSpeech: "emër",
    syllables: "be-sim",
    clue: "Rritet kur fjalët dhe veprat përputhen.",
    definition: "Bindje se dikush është i ndershëm, i aftë ose i sigurt.",
    example: "Ata kanë besim të plotë te njëri-tjetri.",
    region: "standard",
  },
  {
    word: "bregu",
    partOfSpeech: "emër",
    syllables: "bre-gu",
    clue: "Aty takohen toka dhe uji.",
    definition: "Pjesa e tokës që kufizohet me detin, liqenin ose lumin.",
    example: "Bregu ishte i qetë në agim.",
    region: "standard",
  },
  {
    word: "bukur",
    partOfSpeech: "mbiemër",
    syllables: "bu-kur",
    clue: "Të kënaq syrin ose mendjen.",
    definition: "Që ka hijeshi dhe lë përshtypje të këndshme.",
    example: "Pamja nga mali ishte shumë e bukur.",
    region: "standard",
  },
  {
    word: "buxhet",
    partOfSpeech: "emër",
    syllables: "bu-xhet",
    clue: "Plan për çdo lek që hyn e del.",
    definition: "Plan i të ardhurave dhe shpenzimeve për një periudhë.",
    example: "Familja përgatiti buxhetin e muajit.",
    region: "standard",
  },
  {
    word: "cikli",
    partOfSpeech: "emër",
    syllables: "ci-kli",
    clue: "Rikthehet te fillimi pasi mbyllet.",
    definition: "Varg fazash ose ngjarjesh që përsëriten në të njëjtin rend.",
    example: "Cikli i stinëve përsëritet çdo vit.",
    region: "standard",
  },
  {
    word: "çekiç",
    partOfSpeech: "emër",
    syllables: "çe-kiç",
    clue: "Mjeti që punon me gozhdë.",
    definition: "Vegël dore me kokë të rëndë që përdoret për të goditur.",
    example: "Ai nguli gozhdën me çekiç.",
    region: "standard",
  },
  {
    word: "dallgë",
    partOfSpeech: "emër",
    syllables: "dall-gë",
    clue: "Ngrihet e ulet mbi det.",
    definition: "Valë e madhe që formohet në sipërfaqen e ujit.",
    example: "Një dallgë e fortë goditi shkëmbin.",
    region: "standard",
  },
  {
    word: "dardhë",
    partOfSpeech: "emër",
    syllables: "dar-dhë",
    clue: "Frut me bazë të gjerë e majë të ngushtë.",
    definition: "Frut i ëmbël dhe i lëngshëm që rritet në pemën me të njëjtin emër.",
    example: "Ajo zgjodhi një dardhë të pjekur.",
    region: "standard",
  },
  {
    word: "darkë",
    partOfSpeech: "emër",
    syllables: "dar-kë",
    clue: "Vakti që mbyll ditën.",
    definition: "Ushqimi që hahet zakonisht në mbrëmje.",
    example: "Sonte do të hamë darkë së bashku.",
    region: "standard",
  },
  {
    word: "dashur",
    partOfSpeech: "mbiemër / pjesore",
    syllables: "da-shur",
    clue: "I afërt për zemrën.",
    definition: "Që çmohet dhe për të cilin ndihet dashuri.",
    example: "Ai është një mik shumë i dashur.",
    region: "standard",
  },
  {
    word: "detar",
    partOfSpeech: "emër",
    syllables: "de-tar",
    clue: "E njeh mirë jetën mbi ujë.",
    definition: "Njeri që punon në një anije ose merret me lundrim.",
    example: "Detari vrojtoi horizontin nga kuverta.",
    region: "standard",
  },
  {
    word: "dhjetë",
    partOfSpeech: "numëror",
    syllables: "dhje-të",
    clue: "Gishtat e të dyja duarve, së bashku.",
    definition: "Numri natyror që vjen pas nëntës.",
    example: "Në kuti kishte dhjetë lapsa.",
    region: "standard",
  },
  {
    word: "dimër",
    partOfSpeech: "emër",
    syllables: "di-mër",
    clue: "Stina e palltos dhe e borës.",
    definition: "Stina më e ftohtë e vitit, ndërmjet vjeshtës dhe pranverës.",
    example: "Këtë dimër ra shumë borë.",
    region: "standard",
  },
  {
    word: "djalë",
    partOfSpeech: "emër",
    syllables: "dja-lë",
    clue: "Fëmijë ose i ri i gjinisë mashkullore.",
    definition: "Fëmijë mashkull ose burrë në moshë të re.",
    example: "Djali po luante në oborr.",
    region: "standard",
  },
  {
    word: "dritë",
    partOfSpeech: "emër",
    syllables: "dri-të",
    clue: "Na lejon të shohim.",
    definition: "Rrezatim që i bën sendet të dukshme për syrin.",
    example: "Drita e mëngjesit hyri nga dritarja.",
    region: "standard",
  },
  {
    word: "dëgjon",
    partOfSpeech: "folje",
    syllables: "dë-gjon",
    clue: "Kap tingujt me vesh.",
    definition: "Percepton një zë ose tingull nëpërmjet dëgjimit.",
    example: "Ajo dëgjon muzikë gjatë rrugës.",
    region: "standard",
  },
  {
    word: "ëndërr",
    partOfSpeech: "emër",
    syllables: "ën-dërr",
    clue: "Një tregim që mendja krijon në gjumë.",
    definition: "Pamje, ndjenja ose ngjarje që përjetohen gjatë gjumit.",
    example: "Mbrëmë pashë një ëndërr të çuditshme.",
    region: "standard",
  },
  {
    word: "falje",
    partOfSpeech: "emër",
    syllables: "fal-je",
    clue: "Kërkohet pas një gabimi.",
    definition: "Heqja e zemërimit ose e fajit ndaj dikujt.",
    example: "Ai kërkoi falje për vonesën.",
    region: "standard",
  },
  {
    word: "festa",
    partOfSpeech: "emër",
    syllables: "fes-ta",
    clue: "Ditë me urime, muzikë dhe gëzim.",
    definition: "Ngjarje ose ditë që kremtohet me gëzim.",
    example: "Festa vazhdoi deri në mbrëmje.",
    region: "standard",
  },
  {
    word: "fillim",
    partOfSpeech: "emër",
    syllables: "fi-llim",
    clue: "Pika ku nis diçka.",
    definition: "Pjesa ose çasti i parë i një veprimi, kohe a ngjarjeje.",
    example: "Fillimi i tregimit tërhoqi vëmendjen.",
    region: "standard",
  },
  {
    word: "fjalë",
    partOfSpeech: "emër",
    syllables: "fja-lë",
    clue: "Njësi e vogël me kuptim në një fjali.",
    definition: "Njësi e gjuhës që shpreh një kuptim.",
    example: "Ajo zgjodhi fjalën e duhur.",
    region: "standard",
  },
  {
    word: "fshati",
    partOfSpeech: "emër",
    syllables: "fsha-ti",
    clue: "Vendbanim më i vogël se qyteti.",
    definition: "Vendbanim me pak banorë, zakonisht në një zonë rurale.",
    example: "Fshati shtrihej pranë malit.",
    region: "standard",
  },
  {
    word: "gabim",
    partOfSpeech: "emër",
    syllables: "ga-bim",
    clue: "Diçka që nuk doli siç duhej.",
    definition: "Veprim, mendim ose rezultat që nuk është i saktë.",
    example: "E korrigjova gabimin para dorëzimit.",
    region: "standard",
  },
  {
    word: "gjashtë",
    partOfSpeech: "numëror",
    syllables: "gjash-të",
    clue: "Një më shumë se pesë.",
    definition: "Numri natyror që vjen pas pesës.",
    example: "Loja ka gjashtë përpjekje.",
    region: "standard",
  },
  {
    word: "hapur",
    partOfSpeech: "mbiemër / pjesore",
    syllables: "ha-pur",
    clue: "Jo i mbyllur.",
    definition: "Që lejon kalimin, hyrjen ose përdorimin pa pengesë.",
    example: "Dritarja mbeti e hapur gjithë natën.",
    region: "standard",
  },
  {
    word: "harta",
    partOfSpeech: "emër",
    syllables: "har-ta",
    clue: "Tregon vende pa të çuar atje.",
    definition: "Paraqitje e zvogëluar e një territori në një sipërfaqe.",
    example: "Harta tregonte të gjitha rrugët kryesore.",
    region: "standard",
  },
  {
    word: "hundë",
    partOfSpeech: "emër",
    syllables: "hun-dë",
    clue: "Organ i frymëmarrjes dhe nuhatjes.",
    definition: "Pjesa e fytyrës me të cilën marrim frymë dhe nuhasim.",
    example: "Ajri i ftohtë ia skuqte hundën.",
    region: "standard",
  },
  {
    word: "kafshë",
    partOfSpeech: "emër",
    syllables: "kaf-shë",
    clue: "Qenie e gjallë e botës shtazore.",
    definition: "Qenie e gjallë që i përket mbretërisë shtazore.",
    example: "Në pyll pamë një kafshë të egër.",
    region: "standard",
  },
  {
    word: "katër",
    partOfSpeech: "numëror",
    syllables: "ka-tër",
    clue: "Një më pak se pesë.",
    definition: "Numri natyror që vjen pas treshit.",
    example: "Tryeza kishte katër karrige.",
    region: "standard",
  },
  {
    word: "këmbë",
    partOfSpeech: "emër",
    syllables: "këm-bë",
    clue: "Na mban në ecje.",
    definition: "Gjymtyrë e poshtme e trupit që shërben për të qëndruar dhe ecur.",
    example: "Pas shëtitjes i dhembte një këmbë.",
    region: "standard",
  },
  {
    word: "kopsht",
    partOfSpeech: "emër",
    syllables: "kopsht",
    clue: "Vend ku rriten lule, fruta ose perime.",
    definition: "Copë toke e kultivuar pranë shtëpisë ose në një park.",
    example: "Në kopsht lulëzuan trëndafilat.",
    region: "standard",
  },
  {
    word: "korrje",
    partOfSpeech: "emër",
    syllables: "korr-je",
    clue: "Mbledhja e prodhimit kur piqet.",
    definition: "Prerja dhe mbledhja e drithërave ose e kulturave të pjekura.",
    example: "Korrja e grurit nisi në qershor.",
    region: "standard",
  },
  {
    word: "lepur",
    partOfSpeech: "emër",
    syllables: "le-pur",
    clue: "Vrapues i vogël me veshë të gjatë.",
    definition: "Gjitar i vogël barngrënës me veshë të gjatë dhe këmbë të pasme të fuqishme.",
    example: "Lepuri u fsheh pas shkurres.",
    region: "standard",
  },
  {
    word: "letër",
    partOfSpeech: "emër",
    syllables: "le-tër",
    clue: "Mund të futet në një zarf.",
    definition: "Mesazh i shkruar që i dërgohet një personi tjetër.",
    example: "Ajo i dërgoi një letër shoqes.",
    region: "standard",
  },
  {
    word: "libër",
    partOfSpeech: "emër",
    syllables: "li-bër",
    clue: "Ka faqe, kapak dhe një histori brenda.",
    definition: "Vepër e shkruar ose e shtypur, e përbërë nga faqe të lidhura.",
    example: "Mora një libër nga biblioteka.",
    region: "standard",
  },
  {
    word: "llambë",
    partOfSpeech: "emër",
    syllables: "llam-bë",
    clue: "Ndriçon dhomën kur bie errësira.",
    definition: "Pajisje që prodhon dritë, zakonisht me energji elektrike.",
    example: "Llamba mbi tryezë dha një dritë të ngrohtë.",
    region: "standard",
  },
  {
    word: "mësim",
    partOfSpeech: "emër",
    syllables: "më-sim",
    clue: "Një copë dije për t'u përvetësuar.",
    definition: "Njohuri ose aftësi që merret duke studiuar a duke ushtruar.",
    example: "Mësimi i sotëm ishte shumë interesant.",
    region: "standard",
  },
  {
    word: "ngjyrë",
    partOfSpeech: "emër",
    syllables: "ngjy-rë",
    clue: "E kuqe, blu ose e gjelbër.",
    definition: "Veti e dritës që perceptohet nga syri si e kuqe, blu e të tjera.",
    example: "Ajo zgjodhi një ngjyrë të ndezur.",
    region: "standard",
  },
  {
    word: "njohje",
    partOfSpeech: "emër",
    syllables: "njoh-je",
    clue: "Mund të nisë me një prezantim.",
    definition: "Procesi i të mësuarit për dikë ose i krijimit të një lidhjeje me të.",
    example: "Njohja e tyre u kthye në miqësi.",
    region: "standard",
  },
  {
    word: "njëzet",
    partOfSpeech: "numëror",
    syllables: "një-zet",
    clue: "Dy dhjetëshe së bashku.",
    definition: "Numri natyror i barabartë me dy herë dhjetë.",
    example: "Në sallë ishin njëzet veta.",
    region: "standard",
  },
  {
    word: "qytet",
    partOfSpeech: "emër",
    syllables: "qy-tet",
    clue: "Vendbanim me lagje, rrugë dhe shumë banorë.",
    definition: "Qendër e madhe banimi me ndërtesa dhe shërbime të shumta.",
    example: "Qyteti zgjohej herët çdo mëngjes.",
    region: "standard",
  },
  {
    word: "rregull",
    partOfSpeech: "emër",
    syllables: "rre-gull",
    clue: "Tregon çfarë lejohet në lojë.",
    definition: "Normë ose udhëzim që përcakton si duhet vepruar.",
    example: "Çdo lojtar duhet ta respektojë këtë rregull.",
    region: "standard",
  },
  {
    word: "sheqer",
    partOfSpeech: "emër",
    syllables: "she-qer",
    clue: "Kristale të ëmbla për kafe ose ëmbëlsira.",
    definition: "Lëndë ushqimore e ëmbël, zakonisht në formë kristalesh të bardha.",
    example: "Ai hodhi pak sheqer në çaj.",
    region: "standard",
  },
  {
    word: "shkollë",
    partOfSpeech: "emër",
    syllables: "shko-llë",
    clue: "Vend ku nxënësit mësojnë së bashku.",
    definition: "Institucion arsimor ku zhvillohet mësimi.",
    example: "Fëmijët u nisën herët për në shkollë.",
    region: "standard",
  },
  {
    word: "shtrat",
    partOfSpeech: "emër",
    syllables: "shtrat",
    clue: "Vendi ku pushojmë natën.",
    definition: "Mobilie e përgatitur për të fjetur ose për t'u shtrirë.",
    example: "Ai u shtri në shtrat pas një dite të gjatë.",
    region: "standard",
  },
  {
    word: "shtëpi",
    partOfSpeech: "emër",
    syllables: "shtë-pi",
    clue: "Vendi që e quajmë tonin.",
    definition: "Ndërtesë ose hapësirë ku banon një person a familje.",
    example: "Pas udhëtimit u kthyem në shtëpi.",
    region: "standard",
  },
  {
    word: "themel",
    partOfSpeech: "emër",
    syllables: "the-mel",
    clue: "Pjesa që mban një ndërtesë nga poshtë.",
    definition: "Baza e fortë mbi të cilën ngrihet një ndërtesë ose mbështetet diçka.",
    example: "Punëtorët hodhën themelin e shtëpisë.",
    region: "standard",
  },
  {
    word: "thesar",
    partOfSpeech: "emër",
    syllables: "the-sar",
    clue: "Pasuri e çmuar që mund të jetë e fshehur.",
    definition: "Grumbull sendesh me vlerë të madhe, si ar, para ose stoli.",
    example: "Legjenda fliste për një thesar të fshehur.",
    region: "standard",
  },
  {
    word: "thënie",
    partOfSpeech: "emër",
    syllables: "thë-ni-e",
    clue: "Shprehje e shkurtër që mbart një mendim.",
    definition: "Fjali ose shprehje e njohur që përcjell një ide a përvojë.",
    example: "Mësuesja shkroi një thënie në tabelë.",
    region: "standard",
  },
  {
    word: "vajzë",
    partOfSpeech: "emër",
    syllables: "vaj-zë",
    clue: "Fëmijë ose e re e gjinisë femërore.",
    definition: "Fëmijë femër ose grua në moshë të re.",
    example: "Vajza po vizatonte pranë dritares.",
    region: "standard",
  },
  {
    word: "verdhë",
    partOfSpeech: "mbiemër",
    syllables: "ver-dhë",
    clue: "Ngjyra e limonit të pjekur.",
    definition: "Që ka ngjyrën e limonit, të arit ose të diellit.",
    example: "Në vazo çeli një lule e verdhë.",
    region: "standard",
  },
  {
    word: "xunkth",
    partOfSpeech: "emër",
    syllables: "xunkth",
    clue: "Bimë e gjatë që rritet pranë ujit.",
    definition: "Bimë kënetore me kërcell të gjatë, të hollë dhe të drejtë.",
    example: "Xunkthi lëkundej lehtë buzë liqenit.",
    region: "standard",
  },
  {
    word: "xhiron",
    partOfSpeech: "folje",
    syllables: "xhi-ron",
    clue: "Regjistron pamje me kamerë.",
    definition: "Filmon një skenë ose regjistron pamje për një prodhim.",
    example: "Regjisori xhiron skenën e fundit.",
    region: "standard",
  },
  {
    word: "zemër",
    partOfSpeech: "emër",
    syllables: "ze-mër",
    clue: "Rreh pa pushim në kraharor.",
    definition: "Organ muskulor që pompon gjakun nëpër trup.",
    example: "Zemra i rrihte shpejt nga gëzimi.",
    region: "standard",
  },
  {
    word: "zhurmë",
    partOfSpeech: "emër",
    syllables: "zhur-më",
    clue: "Shumë tinguj që prishin qetësinë.",
    definition: "Tërësi tingujsh të fortë, të çrregullt ose të padëshiruar.",
    example: "Zhurma e trafikut hyri nga dritarja.",
    region: "standard",
  },
  {
    word: "zhytur",
    partOfSpeech: "mbiemër / pjesore",
    syllables: "zhy-tur",
    clue: "Krejt poshtë sipërfaqes.",
    definition: "I futur plotësisht në ujë ose në një lëndë tjetër.",
    example: "Guri mbeti i zhytur në ujë.",
    region: "standard",
  },
  {
    word: "balta",
    partOfSpeech: "emër",
    syllables: "bal-ta",
    clue: "Dhé i njomur që të ngjitet në këpucë.",
    definition: "Dhe i përzier me ujë që bëhet i butë dhe ngjitës.",
    example: "Pas shiut, rruga u mbush me baltë.",
    region: "standard",
  },
  {
    word: "banka",
    partOfSpeech: "emër",
    syllables: "ban-ka",
    clue: "Aty njerëzit ruajnë paratë e tyre.",
    definition: "Institucion që ruan, jep dhe menaxhon paratë e njerëzve.",
    example: "Shkova në bankë për të hapur një llogari.",
    region: "standard",
  },
  {
    word: "bishti",
    partOfSpeech: "emër",
    syllables: "bish-ti",
    clue: "Qeni e tund kur gëzohet.",
    definition: "Pjesa e pasme e trupit të shumë kafshëve.",
    example: "Macja e ngriti bishtin lart.",
    region: "standard",
  },
  {
    word: "brumë",
    partOfSpeech: "emër",
    syllables: "bru-më",
    clue: "Nga ai del buka pasi piqet.",
    definition: "Përzierje mielli me ujë që përdoret për të pjekur bukë ose ëmbëlsira.",
    example: "Gjyshja e mbrujti brumin për byrek.",
    region: "standard",
  },
  {
    word: "bujku",
    partOfSpeech: "emër",
    syllables: "buj-ku",
    clue: "E punon tokën për të mbjellë.",
    definition: "Njeriu që merret me punimin e tokës dhe me bujqësi.",
    example: "Bujku doli herët në arë.",
    region: "standard",
  },
  {
    word: "byrek",
    partOfSpeech: "emër",
    syllables: "by-rek",
    clue: "Petë të holla me mbushje brenda.",
    definition: "Gjellë me petë të holla dhe mbushje me djathë, mish ose perime.",
    example: "Për mëngjes hëngrëm byrek me spinaq.",
    region: "standard",
  },
  {
    word: "delja",
    partOfSpeech: "emër",
    syllables: "de-lja",
    clue: "Jep lesh dhe qumësht në kope.",
    definition: "Kafshë shtëpiake e butë që rritet për lesh, mish dhe qumësht.",
    example: "Delja kulloste në livadh.",
    region: "standard",
  },
  {
    word: "dhëmbi",
    partOfSpeech: "emër",
    syllables: "dhëm-bi",
    clue: "I bardhë në gojë, që bluan ushqimin.",
    definition: "Secili nga trupat e fortë në gojë që shërbejnë për të kafshuar dhe përtypur.",
    example: "Fëmijës i doli dhëmbi i parë.",
    region: "standard",
  },
  {
    word: "djathë",
    partOfSpeech: "emër",
    syllables: "dja-thë",
    clue: "Bëhet nga qumështi që mpikset.",
    definition: "Ushqim që përgatitet nga qumështi i mpiksur.",
    example: "Në tryezë kishte bukë dhe djathë.",
    region: "standard",
  },
  {
    word: "dollap",
    partOfSpeech: "emër",
    syllables: "do-llap",
    clue: "Aty i vendos rrobat me radhë.",
    definition: "Mobilie me dyer e rafte për të mbajtur rroba ose sende.",
    example: "I vari xhaketat në dollap.",
    region: "standard",
  },
  {
    word: "druri",
    partOfSpeech: "emër",
    syllables: "dru-ri",
    clue: "Rritet me rrënjë e degë në pyll.",
    definition: "Bimë e madhe me trung të fortë, degë dhe gjethe.",
    example: "Druri i lartë hijezonte oborrin.",
    region: "standard",
  },
  {
    word: "flaka",
    partOfSpeech: "emër",
    syllables: "fla-ka",
    clue: "Gjuha e ndritshme e zjarrit.",
    definition: "Pjesa e ndezur dhe e ndritshme që ngrihet nga një send që digjet.",
    example: "Flaka e qiririt lëkundej nga era.",
    region: "standard",
  },
  {
    word: "flladi",
    partOfSpeech: "emër",
    syllables: "flla-di",
    clue: "Erë e lehtë e freskët në verë.",
    definition: "Frymë ere e lehtë dhe e këndshme.",
    example: "Flladi i mbrëmjes na freskoi.",
    region: "standard",
  },
  {
    word: "flokë",
    partOfSpeech: "emër",
    syllables: "flo-kë",
    clue: "Rriten mbi kokë dhe krihen.",
    definition: "Qimet që mbulojnë kokën e njeriut.",
    example: "Vajza i krihte flokët e gjatë.",
    region: "standard",
  },
  {
    word: "frika",
    partOfSpeech: "emër",
    syllables: "fri-ka",
    clue: "E ndien kur je në rrezik.",
    definition: "Ndjenjë shqetësimi para një rreziku ose kërcënimi.",
    example: "Frika e errësirës ia mori gjumin.",
    region: "standard",
  },
  {
    word: "fruta",
    partOfSpeech: "emër",
    syllables: "fru-ta",
    clue: "Të ëmbla që rriten në pemë.",
    definition: "Prodhime të ëmbla e të lëngshme të pemëve që hahen.",
    example: "Bleva fruta të freskëta në treg.",
    region: "standard",
  },
  {
    word: "gishti",
    partOfSpeech: "emër",
    syllables: "gish-ti",
    clue: "Dora ka pesë të tillë.",
    definition: "Secila nga pjesët e holla e të lëvizshme në fund të dorës ose të këmbës.",
    example: "E tregoi shtëpinë me gisht.",
    region: "standard",
  },
  {
    word: "gjalpë",
    partOfSpeech: "emër",
    syllables: "gjal-pë",
    clue: "I verdhë, del nga ajka e qumështit.",
    definition: "Ushqim yndyror i verdhë që nxirret nga ajka e qumështit.",
    example: "E leu bukën me gjalpë.",
    region: "standard",
  },
  {
    word: "gjoksi",
    partOfSpeech: "emër",
    syllables: "gjok-si",
    clue: "Pjesa e trupit ku rreh zemra.",
    definition: "Pjesa e përparme e trupit midis qafës dhe barkut.",
    example: "E shtrëngoi fëmijën pas gjoksit.",
    region: "standard",
  },
  {
    word: "gjueti",
    partOfSpeech: "emër",
    syllables: "gju-e-ti",
    clue: "Ndjekja e kafshëve të egra në pyll.",
    definition: "Veprimtaria e ndjekjes dhe kapjes së kafshëve të egra.",
    example: "Dolën për gjueti në agim.",
    region: "standard",
  },
  {
    word: "gryka",
    partOfSpeech: "emër",
    syllables: "gry-ka",
    clue: "Kalim i ngushtë mes dy maleve.",
    definition: "Kalim i ngushtë e i thellë midis dy maleve ose shkëmbinjve.",
    example: "Lumi kalonte nëpër grykë.",
    region: "standard",
  },
  {
    word: "gëzim",
    partOfSpeech: "emër",
    syllables: "gë-zim",
    clue: "E ndien kur diçka e mirë ndodh.",
    definition: "Ndjenjë e këndshme kënaqësie dhe hareje.",
    example: "Lajmi na solli gëzim të madh.",
    region: "standard",
  },
  {
    word: "gëzof",
    partOfSpeech: "emër",
    syllables: "gë-zof",
    clue: "Leshi i dendur që ngroh kafshët.",
    definition: "Lëkurë me qime të dendura kafshësh që përdoret për veshje.",
    example: "Dhelpra ka gëzof të kuq.",
    region: "standard",
  },
  {
    word: "hudhra",
    partOfSpeech: "emër",
    syllables: "hudh-ra",
    clue: "Erëz e fortë me thelpinj të bardhë.",
    definition: "Bimë me kokë të përbërë nga thelpinj, që përdoret si erëz.",
    example: "Shtoi pak hudhër në gjellë.",
    region: "standard",
  },
  {
    word: "kajsi",
    partOfSpeech: "emër",
    syllables: "kaj-si",
    clue: "Frut i verdhë vere me bërthamë.",
    definition: "Frut i vogël i ëmbël me lëkurë të verdhë-portokalli dhe bërthamë.",
    example: "Pema e kajsisë ishte plot fruta.",
    region: "standard",
  },
  {
    word: "kazan",
    partOfSpeech: "emër",
    syllables: "ka-zan",
    clue: "Enë e madhe ku zien shumë ujë.",
    definition: "Enë e madhe metalike për të zier ose ngrohur lëngje.",
    example: "Vunë kazanin me ujë mbi zjarr.",
    region: "standard",
  },
  {
    word: "klasa",
    partOfSpeech: "emër",
    syllables: "kla-sa",
    clue: "Dhoma ku mësojnë nxënësit.",
    definition: "Grup nxënësish që mësojnë bashkë ose dhoma ku zhvillohet mësimi.",
    example: "Klasa jonë ka njëzet nxënës.",
    region: "standard",
  },
  {
    word: "kodra",
    partOfSpeech: "emër",
    syllables: "ko-dra",
    clue: "Ngritje toke më e vogël se mali.",
    definition: "Ngritje e vogël natyrore e sipërfaqes së tokës.",
    example: "Shtëpia ndodhet mbi një kodër.",
    region: "standard",
  },
  {
    word: "krahu",
    partOfSpeech: "emër",
    syllables: "kra-hu",
    clue: "Nga supi deri te dora.",
    definition: "Pjesa e trupit që lidh supin me dorën.",
    example: "E mbajti fëmijën në krah.",
    region: "standard",
  },
  {
    word: "kripë",
    partOfSpeech: "emër",
    syllables: "kri-pë",
    clue: "E bardhë, u jep shije gjellëve.",
    definition: "Lëndë e bardhë kristalore që përdoret për t'i dhënë shije ushqimit.",
    example: "Gjellës i mungon pak kripë.",
    region: "standard",
  },
  {
    word: "lajthi",
    partOfSpeech: "emër",
    syllables: "laj-thi",
    clue: "Fryt i vogël me guaskë të fortë.",
    definition: "Frut i vogël me lëvozhgë të fortë dhe thelb të ngrënshëm.",
    example: "Mblodhëm lajthi në vjeshtë.",
    region: "standard",
  },
  {
    word: "lakër",
    partOfSpeech: "emër",
    syllables: "la-kër",
    clue: "Perime me shumë gjethe të mbështjella.",
    definition: "Bimë perimore me gjethe të gjera të mbledhura në formë koke.",
    example: "Gatoi lakër me mish.",
    region: "standard",
  },
  {
    word: "lapsi",
    partOfSpeech: "emër",
    syllables: "lap-si",
    clue: "Shkruan dhe fshihet me gomë.",
    definition: "Vegël e hollë me bërthamë grafiti që përdoret për të shkruar e vizatuar.",
    example: "E mprehu lapsin para mësimit.",
    region: "standard",
  },
  {
    word: "limon",
    partOfSpeech: "emër",
    syllables: "li-mon",
    clue: "Frut i verdhë me shije të thartë.",
    definition: "Frut agrumesh me lëkurë të verdhë dhe lëng të thartë.",
    example: "Shtrydhi një limon në çaj.",
    region: "standard",
  },
  {
    word: "livadh",
    partOfSpeech: "emër",
    syllables: "li-vadh",
    clue: "Fushë e gjelbër me bar për kope.",
    definition: "Sipërfaqe toke e mbuluar me bar, ku kullotin bagëtitë.",
    example: "Lopët kullotnin në livadh.",
    region: "standard",
  },
  {
    word: "llamba",
    partOfSpeech: "emër",
    syllables: "llam-ba",
    clue: "E ndez për të ndriçuar dhomën.",
    definition: "Pajisje që jep dritë kur ndizet.",
    example: "Ndezi llambën në dhomë.",
    region: "standard",
  },
  {
    word: "macja",
    partOfSpeech: "emër",
    syllables: "ma-cja",
    clue: "Mjaullin dhe kap minj.",
    definition: "Kafshë e vogël shtëpiake që mban minjtë larg.",
    example: "Macja flinte mbi karrige.",
    region: "standard",
  },
  {
    word: "mbesa",
    partOfSpeech: "emër",
    syllables: "mbe-sa",
    clue: "Vajza e djalit ose e vajzës tënde.",
    definition: "Vajza e fëmijës ose e vëllait e motrës.",
    example: "Gjyshja luante me mbesën.",
    region: "standard",
  },
  {
    word: "mielli",
    partOfSpeech: "emër",
    syllables: "mi-e-lli",
    clue: "Pluhur i bardhë nga bluarja e grurit.",
    definition: "Lëndë pluhur që del nga bluarja e drithërave dhe përdoret për bukë.",
    example: "E shoshiti miellin para gatimit.",
    region: "standard",
  },
  {
    word: "mjeku",
    partOfSpeech: "emër",
    syllables: "mje-ku",
    clue: "Të viziton kur je i sëmurë.",
    definition: "Njeriu që kuron të sëmurët dhe kujdeset për shëndetin.",
    example: "Mjeku i dha ilaçe të pijë.",
    region: "standard",
  },
  {
    word: "motra",
    partOfSpeech: "emër",
    syllables: "mo-tra",
    clue: "Vajza me të njëjtët prindër si ti.",
    definition: "Femra që ka të njëjtët prindër me një person tjetër.",
    example: "Motra ime është më e madhe se unë.",
    region: "standard",
  },
  {
    word: "ngjala",
    partOfSpeech: "emër",
    syllables: "ngja-la",
    clue: "Peshk i gjatë si gjarpër në ujë.",
    definition: "Peshk i gjatë e i rrëshqitshëm që jeton në ujëra të ëmbla dhe të kripura.",
    example: "Zunë një ngjalë të madhe në liqen.",
    region: "standard",
  },
  {
    word: "pjata",
    partOfSpeech: "emër",
    syllables: "pja-ta",
    clue: "E rrumbullakët, ushqimin e mban sipër.",
    definition: "Enë e cekët ku vihet ushqimi për t'u ngrënë.",
    example: "E ktheu pjatën në lavaman.",
    region: "standard",
  },
  {
    word: "polic",
    partOfSpeech: "emër",
    syllables: "po-lic",
    clue: "Ruan rendin dhe qytetarët.",
    definition: "Punonjës që ruan rendin publik dhe zbatimin e ligjit.",
    example: "Polici drejtonte trafikun.",
    region: "standard",
  },
  {
    word: "pupla",
    partOfSpeech: "emër",
    syllables: "pu-pla",
    clue: "Mbulojnë trupin e zogut.",
    definition: "Formacionet e lehta e të buta që mbulojnë trupin e shpendëve.",
    example: "Puplat e bardha mbuluan folenë.",
    region: "standard",
  },
  {
    word: "putra",
    partOfSpeech: "emër",
    syllables: "pu-tra",
    clue: "Këmba e butë e maces a e qenit.",
    definition: "Pjesa e fundit e këmbës së disa kafshëve, me jastëkë e thonj.",
    example: "Qeni e ngriti putrën për të përshëndetur.",
    region: "standard",
  },
  {
    word: "qershi",
    partOfSpeech: "emër",
    syllables: "qer-shi",
    clue: "Frut i vogël i kuq me bishtin e gjatë.",
    definition: "Frut i vogël i ëmbël e i kuq me një bërthamë brenda.",
    example: "Fëmijët hëngrën qershi nën pemë.",
    region: "standard",
  },
  {
    word: "qeshje",
    partOfSpeech: "emër",
    syllables: "qesh-je",
    clue: "Del në fytyrë kur je i lumtur.",
    definition: "Shprehje gëzimi me buzë dhe zë që tregon hare.",
    example: "Qeshja e saj ngrohu të gjithë dhomën.",
    region: "standard",
  },
  {
    word: "qielli",
    partOfSpeech: "emër",
    syllables: "qi-e-lli",
    clue: "I kaltër lart, ku noton dielli.",
    definition: "Hapësira e gjerë blu që shihet sipër tokës.",
    example: "Qielli ishte plot yje.",
    region: "standard",
  },
  {
    word: "qymyr",
    partOfSpeech: "emër",
    syllables: "qy-myr",
    clue: "I zi, digjet për të dhënë nxehtësi.",
    definition: "Lëndë e zezë djegëse që përdoret për ngrohje.",
    example: "E ndezën sobën me qymyr.",
    region: "standard",
  },
  {
    word: "rosak",
    partOfSpeech: "emër",
    syllables: "ro-sak",
    clue: "Rosa mashkull në pellg.",
    definition: "Shpendi mashkull i rosës.",
    example: "Rosaku notonte para rosave.",
    region: "standard",
  },
  {
    word: "rrezik",
    partOfSpeech: "emër",
    syllables: "rre-zik",
    clue: "Ke nevojë të ruhesh prej tij.",
    definition: "Mundësia që të ndodhë diçka e keqe ose e dëmshme.",
    example: "Rruga e lagësht sjell rrezik.",
    region: "standard",
  },
  {
    word: "rruaza",
    partOfSpeech: "emër",
    syllables: "rru-a-za",
    clue: "Kokrra të vogla që kalohen në fill.",
    definition: "Kokrra të vogla me vrimë që lidhen për zbukurim.",
    example: "Vajza bëri një gjerdan me rruaza.",
    region: "standard",
  },
  {
    word: "rrëfim",
    partOfSpeech: "emër",
    syllables: "rrë-fim",
    clue: "Kur dikush tregon një ngjarje.",
    definition: "Tregim me gojë ose me shkrim i një ngjarjeje.",
    example: "Gjyshi filloi një rrëfim të gjatë.",
    region: "standard",
  },
  {
    word: "salcë",
    partOfSpeech: "emër",
    syllables: "sal-cë",
    clue: "Lëng i trashë që i shtohet gjellës.",
    definition: "Përzierje e lëngshme që shoqëron ose i jep shije ushqimit.",
    example: "Makaronat i hëngri me salcë domatesh.",
    region: "standard",
  },
  {
    word: "shalqi",
    partOfSpeech: "emër",
    syllables: "shal-qi",
    clue: "Frut i madh veror, i kuq brenda.",
    definition: "Frut i madh me lëkurë të gjelbër dhe tul të kuq e të ujshëm.",
    example: "Në verë hëngrëm shalqi të ftohtë.",
    region: "standard",
  },
  {
    word: "shkëmb",
    partOfSpeech: "emër",
    syllables: "shkëmb",
    clue: "Gur i madh e i fortë në mal.",
    definition: "Masë e madhe guri e fortë në natyrë.",
    example: "Dallgët përplaseshin pas shkëmbit.",
    region: "standard",
  },
  {
    word: "shpejt",
    partOfSpeech: "ndajfolje",
    syllables: "shpejt",
    clue: "Pa humbur kohë, me nxitim.",
    definition: "Në mënyrë të shpejtë, brenda pak kohe.",
    example: "Eja shpejt se po fillojmë.",
    region: "standard",
  },
  {
    word: "shpellë",
    partOfSpeech: "emër",
    syllables: "shpe-llë",
    clue: "Zgavër e errët brenda malit.",
    definition: "Zgavër e madhe natyrore në shkëmb ose në mal.",
    example: "Eksploruan një shpellë të thellë.",
    region: "standard",
  },
  {
    word: "shpina",
    partOfSpeech: "emër",
    syllables: "shpi-na",
    clue: "Pjesa e pasme e trupit, prapa gjoksit.",
    definition: "Pjesa e pasme e trupit të njeriut nga qafa te beli.",
    example: "E dhembte shpina nga pesha.",
    region: "standard",
  },
  {
    word: "shpirt",
    partOfSpeech: "emër",
    syllables: "shpirt",
    clue: "Bota e brendshme që nuk shihet.",
    definition: "Thelbi i brendshëm jomaterial i njeriut.",
    example: "E këndoi këngën me gjithë shpirt.",
    region: "standard",
  },
  {
    word: "shtati",
    partOfSpeech: "emër",
    syllables: "shta-ti",
    clue: "Sa i gjatë e i madh është trupi.",
    definition: "Trupi i njeriut sipas gjatësisë dhe formës së tij.",
    example: "Ai është djalë me shtat të lartë.",
    region: "standard",
  },
  {
    word: "shtyllë",
    partOfSpeech: "emër",
    syllables: "shty-llë",
    clue: "Mban çatinë që të mos bjerë.",
    definition: "Trup i gjatë e vertikal që mban peshën e një ndërtese.",
    example: "Çatia mbahej nga katër shtylla.",
    region: "standard",
  },
  {
    word: "speca",
    partOfSpeech: "emër",
    syllables: "spe-ca",
    clue: "Perime të gjelbra a të kuqe, ndonjëherë djegëse.",
    definition: "Perime me tul e zgavër brenda, që hahen të gjalla ose të gatuara.",
    example: "Mbushi specat me oriz.",
    region: "standard",
  },
  {
    word: "stinë",
    partOfSpeech: "emër",
    syllables: "sti-në",
    clue: "Viti ndahet në katër të tilla.",
    definition: "Secila nga katër periudhat e vitit sipas motit.",
    example: "Vjeshta është stina ime e preferuar.",
    region: "standard",
  },
  {
    word: "stuhi",
    partOfSpeech: "emër",
    syllables: "stu-hi",
    clue: "Erë e fortë me shi e bubullima.",
    definition: "Kohë me erë shumë të fortë, shpesh me shi ose borë.",
    example: "Stuhia rrëzoi disa pemë.",
    region: "standard",
  },
  {
    word: "tigan",
    partOfSpeech: "emër",
    syllables: "ti-gan",
    clue: "Enë e cekët ku skuqet ushqimi.",
    definition: "Enë e cekët me bisht që përdoret për të skuqur ushqime.",
    example: "I skuqi vezët në tigan.",
    region: "standard",
  },
  {
    word: "tigri",
    partOfSpeech: "emër",
    syllables: "ti-gri",
    clue: "Mace e madhe e egër me vija.",
    definition: "Kafshë e madhe mishngrënëse me lëkurë të verdhë me vija të zeza.",
    example: "Tigri fshihej mes barishteve.",
    region: "standard",
  },
  {
    word: "trung",
    partOfSpeech: "emër",
    syllables: "trung",
    clue: "Pjesa e trashë e drurit nga rrënja te degët.",
    definition: "Pjesa kryesore e fortë e drurit që mban degët.",
    example: "U ul të pushonte mbi një trung.",
    region: "standard",
  },
  {
    word: "xhezve",
    partOfSpeech: "emër",
    syllables: "xhez-ve",
    clue: "Enë e vogël ku ziehet kafeja.",
    definition: "Enë e vogël metalike me bisht për të zier kafe.",
    example: "E vuri xhezven mbi zjarr.",
    region: "standard",
  },
  {
    word: "çekan",
    partOfSpeech: "emër",
    syllables: "çe-kan",
    clue: "Vegël që i bie gozhdës në kokë.",
    definition: "Vegël me kokë të rëndë që përdoret për të goditur gozhda.",
    example: "E nguli gozhdën me çekan.",
    region: "standard",
  },
  {
    word: "çelik",
    partOfSpeech: "emër",
    syllables: "çe-lik",
    clue: "Metal shumë i fortë nga hekuri.",
    definition: "Lidhje e fortë metalike që përftohet nga hekuri.",
    example: "Ura ishte ndërtuar me çelik.",
    region: "standard",
  },
  {
    word: "çelës",
    partOfSpeech: "emër",
    syllables: "çe-lës",
    clue: "Hap e mbyll bravën e derës.",
    definition: "Vegël e vogël metalike që hap e mbyll një bravë.",
    example: "E humbi çelësin e shtëpisë.",
    region: "standard",
  },
  {
    word: "çezmë",
    partOfSpeech: "emër",
    syllables: "çez-më",
    clue: "E hap dhe rrjedh uji prej saj.",
    definition: "Pajisje nga e cila merret uji kur hapet.",
    example: "E mbylli çezmën që të mos rridhte uji.",
    region: "standard",
  },
  {
    word: "çizme",
    partOfSpeech: "emër",
    syllables: "çiz-me",
    clue: "Këpucë të larta për shi e baltë.",
    definition: "Këpucë të gjata që mbulojnë edhe pjesë të këmbës mbi kyç.",
    example: "Veshi çizmet për të dalë në shi.",
    region: "standard",
  },
  {
    word: "çorap",
    partOfSpeech: "emër",
    syllables: "ço-rap",
    clue: "E vesh në këmbë para këpucës.",
    definition: "Veshje e hollë që mbulon këmbën brenda këpucës.",
    example: "Veshi një palë çorape të leshta.",
    region: "standard",
  },
];

const REQUIRED_METADATA_FIELDS = [
  "word",
  "partOfSpeech",
  "syllables",
  "clue",
  "definition",
  "example",
  "region",
];

const seenAnswers = new Set();

for (const answer of ANSWER_ENTRIES) {
  for (const field of REQUIRED_METADATA_FIELDS) {
    if (typeof answer[field] !== "string" || answer[field].trim() === "") {
      throw new Error(`Answer ${answer.word ?? "<unknown>"} is missing ${field}`);
    }
  }

  const tokens = tokenizeAlbanian(answer.word);
  if (tokens === null || tokens.length !== 5) {
    throw new Error(`${answer.word} is not exactly five Albanian letters`);
  }

  if (answer.word !== answer.word.normalize("NFC").toLocaleLowerCase("sq-AL")) {
    throw new Error(`${answer.word} must be lowercase Unicode NFC`);
  }

  if (answer.region !== "standard") {
    throw new Error(`${answer.word} must be marked as standard Albanian`);
  }

  if (seenAnswers.has(answer.word)) {
    throw new Error(`Duplicate answer: ${answer.word}`);
  }

  seenAnswers.add(answer.word);
}

export const ANSWERS = Object.freeze(ANSWER_ENTRIES.map((answer) => Object.freeze(answer)));

export const ACCEPTED_GUESSES = new Set(ACCEPTED_WORD_SET);

for (const answer of ANSWERS) {
  ACCEPTED_GUESSES.add(answer.word);
}
